name: call-render
on:
  schedule:
    - cron: '7 * * * *'   # 每小时的 07 分，错开高峰
  workflow_dispatch:      # 保留手动按钮
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: curl /test
        run: |
          sleep 20
          curl -f https://tz-d2tz-1.onrender.com/
