name: call-render
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: curl / (delay 20s + retry)
        run: |
          sleep 20
          curl -f --retry 3 --retry-delay 5 --max-time 30 \
            https://tz-d2tz-1.onrender.com/
